services:
  db:
    ports:
      - "5433:5432"
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-shifrator}
      POSTGRES_USER: ${POSTGRES_USER:-shifrator}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shifrator}
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - main
      - amnezia-dns-net

volumes:
  postgres_data:

networks:
  main:
    driver: bridge
  amnezia-dns-net:
    external: true
